# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

task_name: "eval"

params:
  instances: null

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
